blog/blog/Controllers/PanelController.cs
using blog.Data.FileManager;
using blog.Data.Repository;
using blog.Models;
using blog.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace blog.Controllers
{
    [Authorize(Roles ="admin")]
    public class PanelController: Controller
    {
        private IRepository _repo;
        private IFileManager _fileManager;

        public PanelController(
            IRepository repo,
            IFileManager fileManager
            )
        {
            _repo = repo;
            _fileManager = fileManager;
        }
        public IActionResult Index()
        {
            var posts = _repo.GetAllPosts();
            return View(posts);
        }
        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id == null)
                return View(new PostViewModel());
            else
            {
                var post = _repo.GetPost((int)id);
                var result = View(new PostViewModel
                {
                    Title = post.Title,
                    id = post.id,
                    Body = post.Body,
                    CurrentImage = post.Image,
                    Description = post.Description,
                    Category = post.Category,
                    Tags = post.Tags,
                    Legend = post.Legend
                }) ;
                return result;
            }
        }
        [HttpPost]
        public async Task<ActionResult> Edit(PostViewModel vm)
        {
            var post = new Post
            {
                Title = vm.Title,
                Body = vm.Body,
                id = vm.id,
                Description = vm.Description,
                Category = vm.Category,
                Tags = vm.Tags,
                Legend = vm.Legend
            };
            if (vm.Image == null)
                post.Image = vm.CurrentImage;
            else
            {
                post.Image = await _fileManager.SaveImage(vm.Image);
            }
            if (post.id > 0)
                _repo.UpdatePost(post);
            else
                _repo.AddPost(post);

            if (await _repo.SaveChangesAsync())
                return RedirectToAction("Index");
            else
                return View(post);
        }
        [HttpGet]
        public async Task<IActionResult> Remove(int id)
        {
            _repo.RemovePost(id);
            await _repo.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

blog/blog/Views/Panel/Edit.cshtml
@model PostViewModel

@{
}
<link href="~/lib/Trumbowyg-master/dist/ui/trumbowyg.css" rel="stylesheet" />
<div style="margin-top: 4rem" class="edit">
    <form asp-controller="Panel" asp-action="Edit" method="post" enctype="multipart/form-data">
        <input asp-for="id" type="hidden" />
        <div>
            <div class="column2"> <label>Título</label></div>
            <div class="column3 campo"> <input style="width:80%" asp-for="Title" /></div>
        </div>
        <div>
            <div class="column2"><label>Categoria</label></div>
            <div class="column3 campo">
                <select asp-for="Category" style="width:80%" >
                    <option value="Travel">Viagem</option>
                    <option value="Programming">Programação</option>
                    <option value="Photography">Fotografia</option>
                </select>
            </div>
        </div>
        <div>
            <div class="column2"><label>Tags</label></div>
            <div class="column3 campo"><input style="width:80%" asp-for="Tags" /></div>
        </div>
        <div>
            <div class="column2"><label>Resumo</label></div>
            <div class="column3 campo"><input style="width:80%" asp-for="Description" /></div>
        </div>
        <div>
            <div class="column4"><textarea id="editor" asp-for="Body"></textarea></div>
        </div>
        <div>
            <div class="column2"><label>Imagem</label></div>
            <input asp-for="CurrentImage" type="hidden" />
            <div class="column3 campo"><input style="width:80%" asp-for="Image" /></div>
        </div>
        <div>
            <div class="column2"><label>Legenda</label></div>
            <div class="column3 campo"><input style="width:80%" asp-for="Legend" /></div>
        </div>
        <div class="column4"><input class="botao" type="submit" value="Enviar" /></div>
    </form>
</div>
@section scripts{
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="~/lib/Trumbowyg-master/dist/trumbowyg.js"></script>
    <script>
        $('#editor').trumbowyg({
            lang: 'pt-br'
        });
    </script>
}

blog/blog/Views/Panel/Index.cshtml
@model IEnumerable<Post>

@{
}
<div class="panel">
    <div>
        <a class="sublinhado" asp-controller="Panel" asp-action="Edit">
            Adicionar Novo Post
        </a>
    </div>

    <h2 style="margin: 1rem 0rem;">Gerenciar Posts</h2>

    <partial name="_PostsList" model="Model" />
</div>